apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-grpc
  namespace: mlops-hw1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-grpc
  template:
    metadata:
      labels:
        app: mlops-grpc
    spec:
      containers:
        - name: grpc
          image: mlops-hw1-app:latest
          imagePullPolicy: IfNotPresent
          args: ["grpc"]
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: CLEARML_ENABLED
              value: "false"
            - name: DVC_ENABLED
              value: "false"
            - name: DATASETS_DIR
              value: "/app/data/datasets"
            - name: MODELS_DIR
              value: "/app/data/models"
            - name: DATABASE_URL
              value: "sqlite:////app/data/ml_service.db"
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: backend-data
              mountPath: /app/data
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-grpc
  namespace: mlops-hw1
spec:
  selector:
    app: mlops-grpc
  ports:
    - port: 50051
      targetPort: 50051
