"""initial schema

Revision ID: 1ce66751a7ce
Revises: c0f36ff0634c
Create Date: 2026-02-22 00:49:37.578283

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '1ce66751a7ce'
down_revision: Union[str, Sequence[str], None] = 'c0f36ff0634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
