"""initial schema

Revision ID: c0f36ff0634c
Revises: 
Create Date: 2026-02-13 02:50:19.858658

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c0f36ff0634c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
