# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """Основной сервис gRPC"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/mlservice.MLService/HealthCheck',
                request_serializer=ml__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListModelClasses = channel.unary_unary(
                '/mlservice.MLService/ListModelClasses',
                request_serializer=ml__service__pb2.Empty.SerializeToString,
                response_deserializer=ml__service__pb2.ModelClassesResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/mlservice.MLService/ListDatasets',
                request_serializer=ml__service__pb2.Empty.SerializeToString,
                response_deserializer=ml__service__pb2.DatasetListResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/mlservice.MLService/ListModels',
                request_serializer=ml__service__pb2.Empty.SerializeToString,
                response_deserializer=ml__service__pb2.ModelListResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/mlservice.MLService/TrainModel',
                request_serializer=ml__service__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.RetrainModel = channel.unary_unary(
                '/mlservice.MLService/RetrainModel',
                request_serializer=ml__service__pb2.RetrainModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/mlservice.MLService/DeleteModel',
                request_serializer=ml__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/mlservice.MLService/Predict',
                request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__service__pb2.PredictResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """Основной сервис gRPC"""

    def HealthCheck(self, request, context):
        """Статус сервиса"""
        
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelClasses(self, request, context):
        """Список доступных классов моделей"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Список датасетов"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Список моделей"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Обучение новой модели"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrainModel(self, request, context):
        """Переобучение существующей модели"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Удаление модели"""


        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Инференс"""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthRequest.FromString,
                    response_serializer=ml__service__pb2.HealthResponse.SerializeToString,
            ),
            'ListModelClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelClasses,
                    request_deserializer=ml__service__pb2.Empty.FromString,
                    response_serializer=ml__service__pb2.ModelClassesResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=ml__service__pb2.Empty.FromString,
                    response_serializer=ml__service__pb2.DatasetListResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=ml__service__pb2.Empty.FromString,
                    response_serializer=ml__service__pb2.ModelListResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=ml__service__pb2.TrainModelRequest.FromString,
                    response_serializer=ml__service__pb2.TrainModelResponse.SerializeToString,
            ),
            'RetrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrainModel,
                    request_deserializer=ml__service__pb2.RetrainModelRequest.FromString,
                    response_serializer=ml__service__pb2.TrainModelResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=ml__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=ml__service__pb2.DeleteModelResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__service__pb2.PredictRequest.FromString,
                    response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlservice.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlservice.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Основной сервис gRPC"""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/HealthCheck',
            ml__service__pb2.HealthRequest.SerializeToString,
            ml__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/ListModelClasses',
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.ModelClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/ListDatasets',
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.DatasetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/ListModels',
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.ModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/TrainModel',
            ml__service__pb2.TrainModelRequest.SerializeToString,
            ml__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/RetrainModel',
            ml__service__pb2.RetrainModelRequest.SerializeToString,
            ml__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/DeleteModel',
            ml__service__pb2.DeleteModelRequest.SerializeToString,
            ml__service__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.MLService/Predict',
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
